name: flutter_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.8
  rxdart: ^0.28.0
  http: ^1.4.0
  web_socket_channel: ^3.0.3
  flutter_bloc: ^9.1.1

  get_it: ^8.0.3
  google_maps_flutter: ^2.12.2
  change_app_package_name: ^1.5.0
  latlong2: ^0.9.1
  equatable: ^2.0.7
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  geolocator: ^14.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^9.2.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5



flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/images/
        
    
    
                                      